# Generated by Django 2.2.1 on 2019-06-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mode_de_formation', models.CharField(max_length=200)),
                ('Types_de_formation', models.CharField(max_length=200)),
                ('Durée', models.DurationField()),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Client')),
            ],
        ),
    ]
