# Generated by Django 2.2.1 on 2019-06-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Types_de_services', models.CharField(max_length=300)),
                ('Expertise', models.CharField(max_length=300)),
            ],
        ),
    ]
